---

replicas: 1
minimumMasterNodes: 1


esJavaOpts: "-Xmx128m -Xms128m"

resources:
  requests:
    cpu: "50m"
    memory: "128M"
  limits:
    cpu: "100m"
    memory: "256M"


volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 100M



persistence:
  enabled: true
  labels:
    # Add default labels for the volumeClaimTemplate fo the StatefulSet
    enabled: false
  annotations: {}


# Hard means that by default pods will only be scheduled if there are enough nodes for them
# and that they will never end up on the same node. Setting this to soft will do this "best effort"
antiAffinity: "soft"
