apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: issuer-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:  admin@mlambda.net
    privateKeySecretRef:
      name: issuer-prod
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: issuer-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:  admin@mlambda.net
    privateKeySecretRef:
      name: issuer-prod
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token