apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: issuer-dev
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email:  admin@mlambda.net
    privateKeySecretRef:
      name: issuer-dev
    solvers:
    - http01:
        ingress:
          class: nginx

---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: issuer-dev
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email:  admin@mlambda.net
    privateKeySecretRef:
      name: issuer-dev
    solvers:
    - http01:
        ingress:
          class: nginx