
alertmanager:
  persistentVolume:
    enabled: false
    size: 100M
  replicaCount: 1
  resources:
     limits:
       cpu: 10m
       memory: 32Mi
     requests:
       cpu: 10m
       memory: 32Mi

nodeExporter:
  resources:
     limits:
       cpu: 20m
       memory: 50Mi
     requests:
       cpu: 10m
       memory: 30Mi

server:
  persistentVolume:
    enabled: false
    size: 2G
  replicaCount: 1
  resources: 
     limits:
       cpu: 100m
       memory: 400Mi
     requests:
       cpu: 50m
       memory: 200Mi
  retention: "1d"

pushgateway:
  replicaCount: 1
  resources:
     limits:
       cpu: 10m
       memory: 32Mi
     requests:
       cpu: 10m
       memory: 32Mi
  persistentVolume:
    size: 100M
    enabled: false


